server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/identity_service"
    username: postgres
    password: hjoEMY68
  jpa:
    ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        JDBC:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true


